boat: # declare the namespace
  node_DummyEvent: # declare the name of the node to apply the parameters to
    ros__parameters: # boilerplate requirement 
      Waypoint1: [42.469667, -76.503983] # parameter name: value
      Waypoint2: [42.469600, -76.504417] # benedum patio far right
      Waypoint3: [42.469267, -76.504383] # inner right
      Waypoint4: [42.469283, -76.504000] # inner left