boat: # declare the namespace
  node_DummyEvent: # declare the name of the node to apply the parameters to
    ros__parameters: # boilerplate requirement 
      Waypoint1: [42.848266, -70.983825] # parameter name: value
      Waypoint2: [42.848564, -70.982044]
      Waypoint3: [42.850138, -70.979619]
      Waypoint4: [42.851239, -70.982494]