# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/mcu/proto/mcu.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17src/mcu/proto/mcu.proto\"\xf9\x02\n\nTeensyData\x12\x1d\n\x07rc_data\x18\x01 \x01(\x0b\x32\x07.RCDataH\x00\x88\x01\x01\x12\x1e\n\x07\x63ommand\x18\x02 \x01(\x0b\x32\x08.CommandH\x01\x88\x01\x01\x12 \n\x08windvane\x18\x03 \x01(\x0b\x32\t.WindVaneH\x02\x88\x01\x01\x12)\n\rwater_sensors\x18\x04 \x01(\x0b\x32\r.WaterSensorsH\x03\x88\x01\x01\x12\x1a\n\x03gps\x18\x05 \x01(\x0b\x32\x08.GPSDataH\x04\x88\x01\x01\x12\x16\n\x03imu\x18\x06 \x01(\x0b\x32\x04.IMUH\x05\x88\x01\x01\x12\x1c\n\x06servos\x18\x07 \x01(\x0b\x32\x07.ServosH\x06\x88\x01\x01\x12)\n\rcamera_servos\x18\x08 \x01(\x0b\x32\r.CameraServosH\x07\x88\x01\x01\x42\n\n\x08_rc_dataB\n\n\x08_commandB\x0b\n\t_windvaneB\x10\n\x0e_water_sensorsB\x06\n\x04_gpsB\x06\n\x04_imuB\t\n\x07_servosB\x10\n\x0e_camera_servos\"\x84\x02\n\x06RCData\x12\x15\n\rleft_analog_y\x18\x01 \x01(\x05\x12\x16\n\x0eright_analog_x\x18\x02 \x01(\x05\x12\x16\n\x0eright_analog_y\x18\x03 \x01(\x05\x12\x15\n\rleft_analog_x\x18\x04 \x01(\x05\x12\x1a\n\x12\x66ront_left_switch1\x18\x05 \x01(\x05\x12\x1a\n\x12\x66ront_left_switch2\x18\x06 \x01(\x05\x12\x1a\n\x12\x66ront_right_switch\x18\x07 \x01(\x05\x12\x17\n\x0ftop_left_switch\x18\x08 \x01(\x05\x12\x18\n\x10top_right_switch\x18\t \x01(\x05\x12\x15\n\rpotentiometer\x18\n \x01(\x05\"\x16\n\x07\x43ommand\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1e\n\x08WindVane\x12\x12\n\nwind_angle\x18\x01 \x01(\x05\"#\n\x0cWaterSensors\x12\x13\n\x0bwater_level\x18\x01 \x01(\x05\"2\n\x07GPSData\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lon\x18\x02 \x01(\x02\x12\r\n\x05speed\x18\x03 \x01(\x02\"/\n\x03IMU\x12\x0c\n\x04roll\x18\x01 \x01(\x02\x12\r\n\x05pitch\x18\x02 \x01(\x02\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\"3\n\x06Servos\x12\x0c\n\x04sail\x18\x01 \x01(\x05\x12\x0b\n\x03jib\x18\x02 \x01(\x05\x12\x0e\n\x06rudder\x18\x03 \x01(\x05\"*\n\x0c\x43\x61meraServos\x12\x0b\n\x03yaw\x18\x01 \x01(\x05\x12\r\n\x05pitch\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.mcu.proto.mcu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEENSYDATA']._serialized_start=28
  _globals['_TEENSYDATA']._serialized_end=405
  _globals['_RCDATA']._serialized_start=408
  _globals['_RCDATA']._serialized_end=668
  _globals['_COMMAND']._serialized_start=670
  _globals['_COMMAND']._serialized_end=692
  _globals['_WINDVANE']._serialized_start=694
  _globals['_WINDVANE']._serialized_end=724
  _globals['_WATERSENSORS']._serialized_start=726
  _globals['_WATERSENSORS']._serialized_end=761
  _globals['_GPSDATA']._serialized_start=763
  _globals['_GPSDATA']._serialized_end=813
  _globals['_IMU']._serialized_start=815
  _globals['_IMU']._serialized_end=862
  _globals['_SERVOS']._serialized_start=864
  _globals['_SERVOS']._serialized_end=915
  _globals['_CAMERASERVOS']._serialized_start=917
  _globals['_CAMERASERVOS']._serialized_end=959
# @@protoc_insertion_point(module_scope)
