# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/teensy/proto/pi.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19src/teensy/proto/pi.proto\"\xbe\x01\n\x06PiData\x12\x14\n\x07\x63md_yaw\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x16\n\tcmd_pitch\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x15\n\x08\x63md_sail\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x14\n\x07\x63md_jib\x18\x04 \x01(\x05H\x03\x88\x01\x01\x12\x17\n\ncmd_rudder\x18\x05 \x01(\x05H\x04\x88\x01\x01\x42\n\n\x08_cmd_yawB\x0c\n\n_cmd_pitchB\x0b\n\t_cmd_sailB\n\n\x08_cmd_jibB\r\n\x0b_cmd_rudderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.teensy.proto.pi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PIDATA']._serialized_start=30
  _globals['_PIDATA']._serialized_end=220
# @@protoc_insertion_point(module_scope)
