# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: teensy.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'teensy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cteensy.proto\"\xc2\x02\n\x04\x44\x61ta\x12$\n\ncontroller\x18\x01 \x01(\x0b\x32\x0b.ControllerH\x00\x88\x01\x01\x12\x1e\n\x07\x63ommand\x18\x02 \x01(\x0b\x32\x08.CommandH\x01\x88\x01\x01\x12 \n\x08windvane\x18\x03 \x01(\x0b\x32\t.WindVaneH\x02\x88\x01\x01\x12)\n\rwater_sensors\x18\x04 \x01(\x0b\x32\r.WaterSensorsH\x03\x88\x01\x01\x12\x1a\n\x03gps\x18\x05 \x01(\x0b\x32\x08.GPSDataH\x04\x88\x01\x01\x12\x16\n\x03imu\x18\x06 \x01(\x0b\x32\x04.IMUH\x05\x88\x01\x01\x12\x1d\n\x07rc_data\x18\x07 \x01(\x0b\x32\x07.RCDataH\x06\x88\x01\x01\x42\r\n\x0b_controllerB\n\n\x08_commandB\x0b\n\t_windvaneB\x10\n\x0e_water_sensorsB\x06\n\x04_gpsB\x06\n\x04_imuB\n\n\x08_rc_data\"#\n\nController\x12\x15\n\rleft_analog_y\x18\x01 \x01(\x05\"\x84\x02\n\x06RCData\x12\x15\n\rleft_analog_y\x18\x01 \x01(\x05\x12\x16\n\x0eright_analog_x\x18\x02 \x01(\x05\x12\x16\n\x0eright_analog_y\x18\x03 \x01(\x05\x12\x15\n\rleft_analog_x\x18\x04 \x01(\x05\x12\x1a\n\x12\x66ront_left_switch1\x18\x05 \x01(\x05\x12\x1a\n\x12\x66ront_left_switch2\x18\x06 \x01(\x05\x12\x1a\n\x12\x66ront_right_switch\x18\x07 \x01(\x05\x12\x17\n\x0ftop_left_switch\x18\x08 \x01(\x05\x12\x18\n\x10top_right_switch\x18\t \x01(\x05\x12\x15\n\rpotentiometer\x18\n \x01(\x05\"\x16\n\x07\x43ommand\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1e\n\x08WindVane\x12\x12\n\nwind_angle\x18\x01 \x01(\x05\"\x9e\x01\n\x0cWaterSensors\x12\x1b\n\x0esensor1_is_wet\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x1b\n\x0esensor2_is_wet\x18\x02 \x01(\x08H\x01\x88\x01\x01\x12\x1b\n\x0esensor3_is_wet\x18\x03 \x01(\x08H\x02\x88\x01\x01\x42\x11\n\x0f_sensor1_is_wetB\x11\n\x0f_sensor2_is_wetB\x11\n\x0f_sensor3_is_wet\"2\n\x07GPSData\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lon\x18\x02 \x01(\x02\x12\r\n\x05speed\x18\x03 \x01(\x02\"/\n\x03IMU\x12\x0c\n\x04roll\x18\x01 \x01(\x02\x12\r\n\x05pitch\x18\x02 \x01(\x02\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'teensy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATA']._serialized_start=17
  _globals['_DATA']._serialized_end=339
  _globals['_CONTROLLER']._serialized_start=341
  _globals['_CONTROLLER']._serialized_end=376
  _globals['_RCDATA']._serialized_start=379
  _globals['_RCDATA']._serialized_end=639
  _globals['_COMMAND']._serialized_start=641
  _globals['_COMMAND']._serialized_end=663
  _globals['_WINDVANE']._serialized_start=665
  _globals['_WINDVANE']._serialized_end=695
  _globals['_WATERSENSORS']._serialized_start=698
  _globals['_WATERSENSORS']._serialized_end=856
  _globals['_GPSDATA']._serialized_start=858
  _globals['_GPSDATA']._serialized_end=908
  _globals['_IMU']._serialized_start=910
  _globals['_IMU']._serialized_end=957
# @@protoc_insertion_point(module_scope)
