# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controlsData.proto
# docs: https://protobuf.dev/getting-started/pythontutorial/
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ontrolsData.proto\"\xf1\x01\n\x0b\x43ontrolData\x12\x15\n\rleft_analog_x\x18\x01 \x01(\x05\x12\x15\n\rleft_analog_y\x18\x02 \x01(\x05\x12\x16\n\x0eright_analog_x\x18\x03 \x01(\x05\x12\x16\n\x0eright_analog_y\x18\x04 \x01(\x05\x12\x19\n\x11\x66ront_left_switch\x18\x05 \x01(\x05\x12\x1a\n\x12left_potentiometer\x18\x06 \x01(\x05\x12\x1a\n\x12\x66ront_right_switch\x18\x07 \x01(\x05\x12\x17\n\x0ftop_left_switch\x18\x08 \x01(\x05\x12\x18\n\x10top_right_switch\x18\t \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controlsData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONTROLDATA']._serialized_start=23
  _globals['_CONTROLDATA']._serialized_end=264
# @@protoc_insertion_point(module_scope)
